.headers on
.mode columns
PRAGMA FOREIGN_KEYS=ON;
DROP TABLE IF EXISTS EQUIPA;
CREATE TABLE EQUIPA(
    ID INTEGER,
    NOME TEXT NOT NULL UNIQUE,
    PAIS TEXT NOT NULL,
    CONSTRAINT EQUIPA_PK PRIMARY KEY(ID)
);
DROP TABLE IF EXISTS JOGADOR;
CREATE TABLE JOGADOR(
    ID INTEGER,
    EQUIPA TEXT,
    NOME TEXT NOT NULL UNIQUE,
    CONSTRAINT JOGADOR_PK PRIMARY KEY(ID),
    CONSTRAINT EQUIPA_FK FOREIGN KEY(EQUIPA) REFERENCES EQUIPA(NOME) ON DELETE CASCADE
);
DROP TABLE IF EXISTS JOGO;
CREATE TABLE JOGO(
    ID INTEGER,
    JORNADA TEXT NOT NULL,
    DATA DATE NOT NULL,
    equipaCASA TEXT,
    equipaVIS TEXT,
    CASAres INTEGER NOT NULL,
    VISres INTEGER NOT NULL,
    CONSTRAINT JOGO_PK PRIMARY KEY(ID),
    CONSTRAINT EQUIPA_FK FOREIGN KEY(equipaCASA) REFERENCES EQUIPA(NOME) ON DELETE CASCADE,
    CONSTRAINT EQUIPA_FK FOREIGN KEY(equipaVIS) REFERENCES EQUIPA(NOME) ON DELETE CASCADE
);
DROP TABLE IF EXISTS GOLO;
CREATE TABLE GOLO(
    ID INTEGER,
    MINUTO INTEGER NOT NULL,
    EQUIPAfav TEXT,
    MARCADOR TEXT,
    IDjogo INTEGER,
    CONSTRAINT GOLO_PK PRIMARY KEY(ID),
    CONSTRAINT JOGADOR_FK FOREIGN KEY(MARCADOR) REFERENCES JOGADOR(NOME) ON DELETE CASCADE,
    CONSTRAINT EQUIPA_FK FOREIGN KEY(EQUIPAfav) REFERENCES EQUIPA(NOME) ON DELETE CASCADE,
    CONSTRAINT JOGO_FK FOREIGN KEY(IDjogo) REFERENCES JOGO(ID) ON DELETE CASCADE
);
DROP TABLE IF EXISTS EVENTO;
CREATE TABLE EVENTO(
    ID INTEGER,
    TIPO TEXT NOT NULL,
    MINUTO INTEGER NOT NULL,
    IDjogo INTEGER,
    CONSTRAINT EVENTO_PK PRIMARY KEY(ID),
    CONSTRAINT CHK_EVENTO CHECK(TIPO='Cartão' OR TIPO='Substituição'),
    CONSTRAINT JOGO_FK FOREIGN KEY(IDjogo) REFERENCES JOGO(ID) ON DELETE CASCADE
);
DROP TABLE IF EXISTS CARTAO;
CREATE TABLE CARTAO(
    ID INTEGER,
    COR TEXT NOT NULL,
    EQUIPA TEXT,
    JOGADOR TEXT,
    IDevento INTEGER,
    CONSTRAINT CARTAO_PK PRIMARY KEY(ID),
    CONSTRAINT CHK_CARTAO CHECK(COR='Amarelo' OR COR='Vermelho'),
    CONSTRAINT EQUIPA_FK FOREIGN KEY(EQUIPA) REFERENCES EQUIPA(NOME) ON DELETE CASCADE,
    CONSTRAINT JOGADOR_PK FOREIGN KEY(JOGADOR) REFERENCES JOGADOR(NOME) ON DELETE CASCADE,
    CONSTRAINT EVENTO_FK FOREIGN KEY(IDevento) REFERENCES EVENTO(ID) ON DELETE CASCADE
);
DROP TABLE IF EXISTS SUBSTITUICAO;
CREATE TABLE SUBSTITUICAO(
    ID INTEGER,
    EQUIPA TEXT,
    JOGADORent TEXT,
    JOGADORsai TEXT,
    IDevento INTEGER,
    CONSTRAINT SUBSTITUICAO_PK PRIMARY KEY(ID),
    CONSTRAINT EQUIPA_FK FOREIGN KEY(EQUIPA) REFERENCES EQUIPA(NOME) ON DELETE CASCADE,
    CONSTRAINT JOGADOR_PK FOREIGN KEY(JOGADORent) REFERENCES JOGADOR(NOME) ON DELETE CASCADE,
    CONSTRAINT JOGADOR_PK FOREIGN KEY(JOGADORsai) REFERENCES JOGADOR(NOME) ON DELETE CASCADE,
    CONSTRAINT EVENTO_FK FOREIGN KEY(IDevento) REFERENCES EVENTO(ID) ON DELETE CASCADE
);
DROP TABLE IF EXISTS ESTADIO;
CREATE TABLE ESTADIO(
    ID INTEGER,
    NOME TEXT NOT NULL,
    PAIS TEXT NOT NULL,
    IDjogo INTEGER,
    CONSTRAINT ESTADIO_PK PRIMARY KEY(ID),
    CONSTRAINT JOGO_FK FOREIGN KEY(IDjogo) REFERENCES JOGO(ID) ON DELETE CASCADE
)