SELECT NOME FROM EQUIPA;
SELECT * FROM JOGADOR WHERE EQUIPA='Flamengo' OR EQUIPA='Atlético PR' ORDER BY EQUIPA;
DELETE FROM JOGADOR WHERE EQUIPA='Flamengo';
DELETE FROM JOGADOR WHERE NOME='David Terans';
SELECT NOME FROM EQUIPA;
SELECT * FROM JOGADOR WHERE EQUIPA='Flamengo' OR EQUIPA='Atlético PR' ORDER BY EQUIPA;