SELECT * FROM JOGO WHERE ID=1;
SELECT * FROM GOLO WHERE IDjogo=1;
INSERT INTO GOLO VALUES((SELECT COUNT(*) FROM GOLO)+1,50,'Atlético PR','Pablo',1);
INSERT INTO GOLO VALUES((SELECT COUNT(*) FROM GOLO)+1,50,'Flamengo','Gabriel Barbosa',1);
SELECT * FROM GOLO WHERE IDjogo=1;