SELECT * FROM JOGADOR WHERE EQUIPA='Atlético PR';
SELECT * FROM GOLO WHERE IDjogo=29;
INSERT INTO GOLO VALUES(((SELECT COUNT(*) FROM GOLO)+1),50,'Atlético PR','Jogador Novo',29);
INSERT INTO GOLO VALUES(((SELECT COUNT(*) FROM GOLO)+1),50,'Atlético PR','Nicolás Hernández',29);
SELECT * FROM JOGADOR WHERE EQUIPA='Atlético PR';
SELECT * FROM GOLO WHERE IDjogo=29;