DROP TRIGGER IF EXISTS R;
CREATE TRIGGER R
BEFORE INSERT ON GOLO
FOR EACH ROW
WHEN (NEW.MARCADOR NOT IN (SELECT NOME FROM JOGADOR))
BEGIN
INSERT INTO JOGADOR VALUES((SELECT COUNT(*) FROM JOGADOR)+1,NEW.EQUIPAfav,NEW.MARCADOR);
END;