.headers on
.mode columns
PRAGMA FOREIGN_KEYS=ON;
INSERT INTO EQUIPA VALUES(1,'Colón Santa Fe','Argentina');
INSERT INTO EQUIPA VALUES(2,'River Plate','Argentina');
INSERT INTO EQUIPA VALUES(3,'Boca Juniors','Argentina');
INSERT INTO EQUIPA VALUES(4,'Vélez Sarsfield','Argentina');
INSERT INTO EQUIPA VALUES(5,'Talleres de Cordoba','Argentina');
INSERT INTO EQUIPA VALUES(6,'Estudiantes','Argentina');
INSERT INTO EQUIPA VALUES(7,'Independiente Petrolero','Bolívia');
INSERT INTO EQUIPA VALUES(8,'Always Ready','Bolívia');
INSERT INTO EQUIPA VALUES(9,'The Strongest','Bolívia');
INSERT INTO EQUIPA VALUES(10,'Bolívar','Bolívia');
INSERT INTO EQUIPA VALUES(11,'Palmeiras','Brasil');
INSERT INTO EQUIPA VALUES(12,'Atlético PR','Brasil');
INSERT INTO EQUIPA VALUES(13,'Atlético Mineiro','Brasil');
INSERT INTO EQUIPA VALUES(14,'Flamengo','Brasil');
INSERT INTO EQUIPA VALUES(15,'Fortaleza','Brasil');
INSERT INTO EQUIPA VALUES(16,'Corinthians','Brasil');
INSERT INTO EQUIPA VALUES(17,'Red Bull Bragantino','Brasil');
INSERT INTO EQUIPA VALUES(18,'Fluminense','Brasil');
INSERT INTO EQUIPA VALUES(19,'América Mineiro','Brasil');
INSERT INTO EQUIPA VALUES(20,'Universidad Católica','Chile');
INSERT INTO EQUIPA VALUES(21,'Colo-Colo','Chile');
INSERT INTO EQUIPA VALUES(22,'Audax Italiano','Chile');
INSERT INTO EQUIPA VALUES(23,'Everton','Chile');
INSERT INTO EQUIPA VALUES(24,'Tolima','Colômbia');
INSERT INTO EQUIPA VALUES(25,'Deportivo Cali','Colômbia');
INSERT INTO EQUIPA VALUES(26,'Millonarios','Colômbia');
INSERT INTO EQUIPA VALUES(27,'Atlético Nacional','Colômbia');
INSERT INTO EQUIPA VALUES(28,'Independiente del Valle','Equador');
INSERT INTO EQUIPA VALUES(29,'Emelec','Equador');
INSERT INTO EQUIPA VALUES(30,'Universidad Católica del Ecuador','Equador');
INSERT INTO EQUIPA VALUES(31,'Barcelona SC','Equador');
INSERT INTO EQUIPA VALUES(32,'Cerro Porteño','Paraguai');
INSERT INTO EQUIPA VALUES(33,'Libertad','Paraguai');
INSERT INTO EQUIPA VALUES(34,'Guaraní','Paraguai');
INSERT INTO EQUIPA VALUES(35,'Olimpia','Paraguai');
INSERT INTO EQUIPA VALUES(36,'Alianza Lima','Peru');
INSERT INTO EQUIPA VALUES(37,'Sporting Cristal','Peru');
INSERT INTO EQUIPA VALUES(38,'Universitario','Peru');
INSERT INTO EQUIPA VALUES(39,'Universidad César Vallejo','Peru');
INSERT INTO EQUIPA VALUES(40,'Peñarol','Uruguai');
INSERT INTO EQUIPA VALUES(41,'Nacional','Uruguai');
INSERT INTO EQUIPA VALUES(42,'Plaza Colonia','Uruguai');
INSERT INTO EQUIPA VALUES(43,'Montevideo City Torque','Uruguai');
INSERT INTO EQUIPA VALUES(44,'Deportivo Táchira','Venezuela');
INSERT INTO EQUIPA VALUES(45,'Caracas','Venezuela');
INSERT INTO EQUIPA VALUES(46,'Monagas','Venezuela');
INSERT INTO EQUIPA VALUES(47,'Deportivo Lara','Venezuela');
INSERT INTO JOGADOR VALUES(1,'Flamengo','Gabriel Barbosa');
INSERT INTO JOGADOR VALUES(2,'Vélez Sarsfield','Lucas Pratto');
INSERT INTO JOGADOR VALUES(3,'Flamengo','Pedro');
INSERT INTO JOGADOR VALUES(4,'Flamengo','Marinho');
INSERT INTO JOGADOR VALUES(5,'Palmeiras','Gustavo Scarpa');
INSERT INTO JOGADOR VALUES(6,'Palmeiras','Gustavo Portillo');
INSERT INTO JOGADOR VALUES(7,'Atlético PR','Pablo');
INSERT INTO JOGADOR VALUES(8,'Atlético PR','David Terans');
INSERT INTO JOGADOR VALUES(9,'Flamengo','Éverton Ribeiro');
INSERT INTO JOGADOR VALUES(10,'Atlético PR','Alex Santana');
INSERT INTO JOGADOR VALUES(11,'Atlético PR','Vitor Roque');
INSERT INTO JOGADOR VALUES(12,'Vélez Sarsfield','Julián Fernández');
INSERT INTO JOGADOR VALUES(13,'Vélez Sarsfield','Lucas Janson');
INSERT INTO JOGADOR VALUES(14,'Talleres de Cordoba','Michael Santos');
INSERT INTO JOGADOR VALUES(15,'Talleres de Cordoba','Rodrigo Garro');
INSERT INTO JOGADOR VALUES(16,'Atlético Mineiro','Hulk');
INSERT INTO JOGADOR VALUES(17,'Palmeiras','Murilo Cerqueira');
INSERT INTO JOGADOR VALUES(18,'Palmeiras','Danilo');
INSERT INTO JOGADOR VALUES(19,'Flamengo','Giorgian de Arrascaeta');
INSERT INTO JOGADOR VALUES(20,'Estudiantes','Manuel Castro');
INSERT INTO JOGADOR VALUES(21,'Estudiantes','Franco Zapiola');
INSERT INTO JOGADOR VALUES(22,'Talleres de Cordoba','Federico Girotti');
INSERT INTO JOGADOR VALUES(23,'Talleres de Cordoba','Angelo Martino');
INSERT INTO JOGADOR VALUES(24,'Tolima','Julián Quiñones');
INSERT INTO JOGADOR VALUES(25,'Flamengo','Matheus França');
INSERT INTO JOGADOR VALUES(26,'Cerro Porteño','Braian Samudio');
INSERT INTO JOGADOR VALUES(27,'Palmeiras','Rony');
INSERT INTO JOGADOR VALUES(28,'Palmeiras','Bren Lopes');
INSERT INTO JOGADOR VALUES(29,'Palmeiras','Gustavo Gómez');
INSERT INTO JOGADOR VALUES(30,'Libertad','Roque Cantero');
INSERT INTO JOGADOR VALUES(31,'Atlético PR','Rômulo Cardoso');
INSERT INTO JOGADOR VALUES(32,'Fortaleza','Silvio Romero');
INSERT INTO JOGADOR VALUES(33,'Estudiantes','Leandro Díaz');
INSERT INTO JOGADOR VALUES(34,'Colón Santa Fe','Ramón Ábila');
INSERT INTO JOGADOR VALUES(35,'Talleres de Cordoba','Alan Franco');
INSERT INTO JOGADOR VALUES(36,'Flamengo','Andreas Pereira');
INSERT INTO JOGADOR VALUES(37,'Atlético Mineiro','Ademir');
INSERT INTO JOGADOR VALUES(38,'Emelec','Sebestián Rodríguez');
INSERT INTO JOGADOR VALUES(39,'Libertad','Héctor Villalba');
INSERT INTO JOGADOR VALUES(40,'Atlético PR','Nicolás Hernández');
INSERT INTO JOGADOR VALUES(41,'Atlético PR','Pedro Henrique');
INSERT INTO JOGADOR VALUES(42,'Flamengo','Arturo Vidal');
INSERT INTO JOGADOR VALUES(43,'Flamengo','Filipe Luís');
INSERT INTO JOGADOR VALUES(44,'Vélez Sarsfield','Nicolás Garayalde');
INSERT INTO JOGADOR VALUES(45,'Vélez Sarsfield','Mateo Seoane');
INSERT INTO JOGADOR VALUES(46,'Vélez Sarsfield','Miguel Brizuela');
INSERT INTO JOGADOR VALUES(47,'Palmeiras','Gabriel Menino');
INSERT INTO JOGADOR VALUES(48,'Atlético PR','Agustín Canobbio');
INSERT INTO JOGADOR VALUES(49,'Atlético PR','Pedrinho');
INSERT INTO JOGADOR VALUES(50,'Atlético PR','Thiago Heleno');
INSERT INTO JOGADOR VALUES(51,'Palmeiras','Weverton');
INSERT INTO JOGADOR VALUES(52,'Vélez Sarsfield','Valentín Gómez');
INSERT INTO JOGADOR VALUES(53,'Flamengo','Thiago Maia');
INSERT INTO JOGADOR VALUES(54,'Vélez Sarsfield','Matías De los Santos');
INSERT INTO JOGADOR VALUES(55,'Flamengo','David Luiz');
INSERT INTO JOGADOR VALUES(56,'Flamengo','Léo Pereira');
INSERT INTO JOGADOR VALUES(57,'Flamengo','Erick Pulgar');
INSERT INTO JOGADOR VALUES(58,'Palmeiras','Zé Rafael');
INSERT INTO JOGADOR VALUES(59,'Atlético PR','Hugo Moura');
INSERT INTO JOGADOR VALUES(60,'Flamengo','Ayrton Lucas');
INSERT INTO JOGADOR VALUES(61,'Atlético PR','Matheus Nascimento');
INSERT INTO JOGADOR VALUES(62,'Atlético PR','Vítor Bueno');
INSERT INTO JOGADOR VALUES(63,'Atlético PR','Vitinho');
INSERT INTO JOGADOR VALUES(64,'Flamengo','Everton Soares');
INSERT INTO JOGADOR VALUES(65,'Flamengo','Victor Hugo');
INSERT INTO JOGADOR VALUES(66,'Flamengo','Luca Orellano');
INSERT INTO JOGADOR VALUES(67,'Vélez Sarsfield','Walter Bou');
INSERT INTO JOGADOR VALUES(68,'Vélez Sarsfield','Abiel Osorio');
INSERT INTO JOGADOR VALUES(69,'Vélez Sarsfield','José Florentín');
INSERT INTO JOGADOR VALUES(70,'Vélez Sarsfield','Santiago Cáseres');
INSERT INTO JOGADOR VALUES(71,'Flamengo','Guillermo Varela');
INSERT INTO JOGADOR VALUES(72,'Flamengo','Diego');
INSERT INTO JOGADOR VALUES(73,'Vélez Sarsfield','Santiago Castro');
INSERT INTO JOGADOR VALUES(74,'Atlético PR','Abner Vinícius');
INSERT INTO JOGADOR VALUES(75,'Palmeiras','Luan Garcia');
INSERT INTO JOGADOR VALUES(76,'Palmeiras','Bruno Tabata');
INSERT INTO JOGADOR VALUES(77,'Atlético PR','Erick');
INSERT INTO JOGADOR VALUES(78,'Palmeiras','Mayke');
INSERT INTO JOGADOR VALUES(79,'Palmeiras','Marcos Rocha');
INSERT INTO JOGADOR VALUES(80,'Palmeiras','Wesley');
INSERT INTO JOGADOR VALUES(81,'Palmeiras','Miguel Merentiel');
INSERT INTO JOGADOR VALUES(82,'Palmeiras','Joaquín Piquerez');
INSERT INTO JOGADOR VALUES(83,'Palmeiras','Eduard Atuesta');
INSERT INTO JOGADOR VALUES(84,'Atlético PR','Matheus Fernandes');
INSERT INTO JOGADOR VALUES(85,'Flamengo','João Gomes');
INSERT INTO JOGADOR VALUES(86,'Palmeiras','Raphael Veiga');
INSERT INTO JOGADOR VALUES(87,'Palmeiras','José Lopéz');
INSERT INTO JOGADOR VALUES(88,'Palmeiras','Raphael Navarro');
INSERT INTO JOGADOR VALUES(89,'Atlético PR','Tomás Cuello');
INSERT INTO JOGADOR VALUES(90,'Atlético PR','Léo Cittadini');
INSERT INTO JOGADOR VALUES(91,'Atlético PR','Fernandinho');
INSERT INTO JOGO VALUES(1,'Final','29/10/2022','Flamengo','Atlético PR',1,0);
INSERT INTO JOGO VALUES(2,'Semifinal','8/09/2022','Flamengo','Vélez Sarsfield',2,1);
INSERT INTO JOGO VALUES(3,'Semifinal','7/09/2022','Palmeiras','Atlético PR',2,2);
INSERT INTO JOGO VALUES(4,'Semifinal','1/09/2022','Vélez Sarsfield','Flamengo',0,4);
INSERT INTO JOGO VALUES(5,'Semifinal','31/08/2022','Atlético PR','Palmeiras',1,0);
INSERT INTO JOGO VALUES(6,'Quarterfinal','12/08/2022','Estudiantes','Atlético PR',0,1);
INSERT INTO JOGO VALUES(7,'Quarterfinal','11/08/2022','Palmeiras','Atlético Mineiro',0,0);
INSERT INTO JOGO VALUES(8,'Quarterfinal','11/08/2022','Talleres de Cordoba','Vélez Sarsfield',0,1);
INSERT INTO JOGO VALUES(9,'Quarterfinal','10/08/2022','Flamengo','Corinthians',1,0);
INSERT INTO JOGO VALUES(10,'Quarterfinal','5/08/2022','Atlético PR','Estudiantes',0,0);
INSERT INTO JOGO VALUES(11,'Quarterfinal','4/08/2022','Vélez Sarsfield','Talleres de Cordoba',3,2);
INSERT INTO JOGO VALUES(12,'Quarterfinal','4/08/2022','Atlético Mineiro','Palmeiras',2,2);
INSERT INTO JOGO VALUES(13,'Quarterfinal','3/08/2022','Corinthians','Flamengo',0,2);
INSERT INTO JOGO VALUES(14,'Round of 16','8/07/2022','Estudiantes','Fortaleza',3,0);
INSERT INTO JOGO VALUES(15,'Round of 16','7/07/2022','River Plate','Vélez Sarsfield',0,0);
INSERT INTO JOGO VALUES(16,'Round of 16','7/07/2022','Colón Santa Fe','Talleres de Cordoba',0,2);
INSERT INTO JOGO VALUES(17,'Round of 16','7/07/2022','Flamengo','Tolima',7,1);
INSERT INTO JOGO VALUES(18,'Round of 16','7/07/2022','Palmeiras','Cerro Porteño',5,0);
INSERT INTO JOGO VALUES(19,'Round of 16','6/07/2022','Boca Juniors','Corinthians',0,0);
INSERT INTO JOGO VALUES(20,'Round of 16','6/07/2022','Atlético Mineiro','Emelec',1,0);
INSERT INTO JOGO VALUES(21,'Round of 16','6/07/2022','Libertad','Atlético PR',1,1);
INSERT INTO JOGO VALUES(22,'Round of 16','1/07/2022','Fortaleza','Estudiantes',1,1);
INSERT INTO JOGO VALUES(23,'Round of 16','30/06/2022','Vélez Sarsfield','River Plate',1,0);
INSERT INTO JOGO VALUES(24,'Round of 16','30/06/2022','Talleres de Cordoba','Colón Santa Fe',1,1);
INSERT INTO JOGO VALUES(25,'Round of 16','30/06/2022','Cerro Porteño','Palmeiras',0,3);
INSERT INTO JOGO VALUES(26,'Round of 16','30/06/2022','Tolima','Flamengo',0,1);
INSERT INTO JOGO VALUES(27,'Round of 16','29/06/2022','Corinthians','Boca Juniors',0,0);
INSERT INTO JOGO VALUES(28,'Round of 16','29/06/2022','Emelec','Atlético Mineiro',1,1);
INSERT INTO JOGO VALUES(29,'Round of 16','29/06/2022','Atlético PR','Libertad',2,1);
INSERT INTO JOGO VALUES(30,'Group Matchday 6','27/05/2022','Atlético PR','Caracas',5,1);
INSERT INTO JOGO VALUES(31,'Group Matchday 6','27/05/2022','Libertad','The Strongest',4,1);
INSERT INTO JOGO VALUES(32,'Group Matchday 6','27/05/2022','Boca Juniors','Deportivo Cali',1,0);
INSERT INTO JOGO VALUES(33,'Group Matchday 6','27/05/2022','Corinthians','Always Ready',1,1);
INSERT INTO JOGO VALUES(34,'Group Matchday 6','26/05/2022','Atlético Mineiro','Tolima',1,2);
INSERT INTO JOGO VALUES(35,'Group Matchday 6','26/05/2022','Independiente del Valle','América Mineiro',3,0);
INSERT INTO JOGO VALUES(36,'Group Matchday 6','26/05/2022','River Plate','Alianza Lima',8,1);
INSERT INTO JOGO VALUES(37,'Group Matchday 6','26/05/2022','Colo-Colo','Fortaleza',3,4);
INSERT INTO JOGO VALUES(38,'Group Matchday 6','26/05/2022','Peñarol','Colón Santa Fe',2,1);
INSERT INTO JOGO VALUES(39,'Group Matchday 6','26/05/2022','Cerro Porteño','Olimpia',0,1);
INSERT INTO JOGO VALUES(40,'Group Matchday 6','25/05/2022','Emelec','Independiente Petrolero',7,0);
INSERT INTO JOGO VALUES(41,'Group Matchday 6','25/05/2022','Palmeiras','Deportivo Táchira',4,1);
INSERT INTO JOGO VALUES(42,'Group Matchday 6','25/05/2022','Nacional','Red Bull Bragantino',3,0);
INSERT INTO JOGO VALUES(43,'Group Matchday 6','25/05/2022','Vélez Sarsfield','Estudiantes',4,0);
INSERT INTO JOGO VALUES(44,'Group Matchday 6','25/05/2022','Universidad Católica','Talleres de Cordoba',0,1);
INSERT INTO JOGO VALUES(45,'Group Matchday 6','25/05/2022','Flamengo','Sporting Cristal',2,1);
INSERT INTO JOGO VALUES(46,'Group Matchday 5','20/05/2022','Atlético Mineiro','Independiente del Valle',3,1);
INSERT INTO JOGO VALUES(47,'Group Matchday 5','20/05/2022','Deportivo Cali','Always Ready',3,0);
INSERT INTO JOGO VALUES(48,'Group Matchday 5','20/05/2022','River Plate','Colo-Colo',4,0);
INSERT INTO JOGO VALUES(49,'Group Matchday 5','19/05/2022','Deportivo Táchira','Independiente Petrolero',3,0);
INSERT INTO JOGO VALUES(50,'Group Matchday 5','19/05/2022','Palmeiras','Emelec',1,0);
INSERT INTO JOGO VALUES(51,'Group Matchday 5','19/05/2022','Atlético PR','Libertad',2,0);
INSERT INTO JOGO VALUES(52,'Group Matchday 5','19/05/2022','Nacional','Vélez Sarsfield',2,3);
INSERT INTO JOGO VALUES(53,'Group Matchday 5','19/05/2022','Tolima','América Mineiro',2,2);
INSERT INTO JOGO VALUES(54,'Group Matchday 5','19/05/2022','Alianza Lima','Fortaleza',0,2);
INSERT INTO JOGO VALUES(55,'Group Matchday 5','19/05/2022','Colón Santa Fe','Olimpia',2,1);
INSERT INTO JOGO VALUES(56,'Group Matchday 5','18/05/2022','Caracas','The Strongest',0,0);
INSERT INTO JOGO VALUES(57,'Group Matchday 5','18/05/2022','Red Bull Bragantino','Estudiantes',0,1);
INSERT INTO JOGO VALUES(58,'Group Matchday 5','18/05/2022','Boca Juniors','Corinthians',1,1);
INSERT INTO JOGO VALUES(59,'Group Matchday 5','18/05/2022','Peñarol','Cerro Porteño',0,0);
INSERT INTO JOGO VALUES(60,'Group Matchday 5','18/05/2022','Flamengo','Universidad Católica',3,0);
INSERT INTO JOGO VALUES(61,'Group Matchday 5','18/05/2022','Sporting Cristal','Talleres de Cordoba',0,0);
INSERT INTO JOGO VALUES(62,'Group Matchday 4','6/05/2022','Red Bull Bragantino','Vélez Sarsfield',1,1);
INSERT INTO JOGO VALUES(63,'Group Matchday 4','6/05/2022','Fortaleza','River Plate',1,1);
INSERT INTO JOGO VALUES(64,'Group Matchday 4','6/05/2022','Alianza Lima','Colo-Colo',1,1);
INSERT INTO JOGO VALUES(65,'Group Matchday 4','5/05/2022','Tolima','Independiente del Valle',1,0);
INSERT INTO JOGO VALUES(66,'Group Matchday 4','5/05/2022','Always Ready','Boca Juniors',0,1);
INSERT INTO JOGO VALUES(67,'Group Matchday 4','5/05/2022','Deportivo Cali','Corinthians',0,0);
INSERT INTO JOGO VALUES(68,'Group Matchday 4','5/05/2022','Olimpia','Peñarol',1,0);
INSERT INTO JOGO VALUES(69,'Group Matchday 4','5/05/2022','Colón Santa Fe','Cerro Porteño',2,1);
INSERT INTO JOGO VALUES(70,'Group Matchday 4','5/05/2022','Sporting Cristal','Universidad Católica',1,1);
INSERT INTO JOGO VALUES(71,'Group Matchday 4','5/05/2022','Talleres de Cordoba','Flamengo',2,2);
INSERT INTO JOGO VALUES(72,'Group Matchday 4','4/05/2022','Independiente Petrolero','Palmeiras',0,5);
INSERT INTO JOGO VALUES(73,'Group Matchday 4','4/05/2022','Deportivo Táchira','Emelec',1,4);
INSERT INTO JOGO VALUES(74,'Group Matchday 4','4/05/2022','The Strongest','Atlético PR',5,0);
INSERT INTO JOGO VALUES(75,'Group Matchday 4','4/05/2022','Caracas','Libertad',1,0);
INSERT INTO JOGO VALUES(76,'Group Matchday 4','4/05/2022','Estudiantes','Nacional',1,0);
INSERT INTO JOGO VALUES(77,'Group Matchday 4','4/05/2022','América Mineiro','Atlético Mineiro',1,2);
INSERT INTO JOGO VALUES(78,'Group Matchday 3','29/04/2022','Always Ready','Deportivo Cali',2,2);
INSERT INTO JOGO VALUES(79,'Group Matchday 3','29/04/2022','Olimpia','Colón Santa Fe',0,0);
INSERT INTO JOGO VALUES(80,'Group Matchday 3','29/04/2022','Universidad Católica','Flamengo',2,3);
INSERT INTO JOGO VALUES(81,'Group Matchday 3','28/04/2022','Emelec','Palmeiras',1,3);
INSERT INTO JOGO VALUES(82,'Group Matchday 3','28/04/2022','The Strongest','Caracas',1,1);
INSERT INTO JOGO VALUES(83,'Group Matchday 3','28/04/2022','América Mineiro','Tolima',2,3);
INSERT INTO JOGO VALUES(84,'Group Matchday 3','28/04/2022','Fortaleza','Alianza Lima',2,1);
INSERT INTO JOGO VALUES(85,'Group Matchday 3','28/04/2022','Colo-Colo','River Plate',1,2);
INSERT INTO JOGO VALUES(86,'Group Matchday 3','28/04/2022','Cerro Porteño','Peñarol',1,0);
INSERT INTO JOGO VALUES(87,'Group Matchday 3','27/04/2022','Independiente Petrolero','Deportivo Táchira',1,2);
INSERT INTO JOGO VALUES(88,'Group Matchday 3','27/04/2022','Libertad','Atlético PR',1,0);
INSERT INTO JOGO VALUES(89,'Group Matchday 3','27/04/2022','Estudiantes','Red Bull Bragantino',2,0);
INSERT INTO JOGO VALUES(90,'Group Matchday 3','27/04/2022','Vélez Sarsfield','Nacional',1,2);
INSERT INTO JOGO VALUES(91,'Group Matchday 3','27/04/2022','Independiente del Valle','Atlético Mineiro',1,1);
INSERT INTO JOGO VALUES(92,'Group Matchday 3','27/04/2022','Corinthians','Boca Juniors',2,0);
INSERT INTO JOGO VALUES(93,'Group Matchday 3','27/04/2022','Talleres de Cordoba','Sporting Cristal',1,0);
INSERT INTO JOGO VALUES(94,'Group Matchday 2','15/04/2022','Emelec','Deportivo Táchira',1,1);
INSERT INTO JOGO VALUES(95,'Group Matchday 2','15/04/2022','Atlético PR','The Strongest',1,0);
INSERT INTO JOGO VALUES(96,'Group Matchday 2','15/04/2022','Vélez Sarsfield','Red Bull Bragantino',2,2);
INSERT INTO JOGO VALUES(97,'Group Matchday 2','14/04/2022','Libertad','Caracas',2,1);
INSERT INTO JOGO VALUES(98,'Group Matchday 2','14/04/2022','Nacional','Estudiantes',0,0);
INSERT INTO JOGO VALUES(99,'Group Matchday 2','14/04/2022','Atlético Mineiro','América Mineiro',1,1);
INSERT INTO JOGO VALUES(100,'Group Matchday 2','14/04/2022','Independiente del Valle','Tolima',2,2);
INSERT INTO JOGO VALUES(101,'Group Matchday 2','14/04/2022','Corinthians','Deportivo Cali',1,0);
INSERT INTO JOGO VALUES(102,'Group Matchday 2','14/04/2022','River Plate','Fortaleza',2,0);
INSERT INTO JOGO VALUES(103,'Group Matchday 2','14/04/2022','Colo-Colo','Alianza Lima',2,1);
INSERT INTO JOGO VALUES(104,'Group Matchday 2','13/04/2022','Palmeiras','Independiente Petrolero',8,1);
INSERT INTO JOGO VALUES(105,'Group Matchday 2','13/04/2022','Boca Juniors','Always Ready',2,0);
INSERT INTO JOGO VALUES(106,'Group Matchday 2','13/04/2022','Peñarol','Olimpia',2,1);
INSERT INTO JOGO VALUES(107,'Group Matchday 2','13/04/2022','Cerro Porteño','Colón Santa Fe',3,1);
INSERT INTO JOGO VALUES(108,'Group Matchday 2','13/04/2022','Universidad Católica','Sporting Cristal',2,1);
INSERT INTO JOGO VALUES(109,'Group Matchday 2','13/04/2022','Flamengo','Talleres de Cordoba',3,1);
INSERT INTO JOGO VALUES(110,'Group Matchday 1','8/04/2022','The Strongest','Libertad',1,1);
INSERT INTO JOGO VALUES(111,'Group Matchday 1','8/04/2022','Estudiantes','Vélez Sarsfield',4,1);
INSERT INTO JOGO VALUES(112,'Group Matchday 1','8/04/2022','Fortaleza','Colo-Colo',1,2);
INSERT INTO JOGO VALUES(113,'Group Matchday 1','7/04/2022','Independiente Petrolero','Emelec',1,1);
INSERT INTO JOGO VALUES(114,'Group Matchday 1','7/04/2022','Deportivo Táchira','Palmeiras',0,4);
INSERT INTO JOGO VALUES(115,'Group Matchday 1','7/04/2022','Red Bull Bragantino','Nacional',2,0);
INSERT INTO JOGO VALUES(116,'Group Matchday 1','7/04/2022','América Mineiro','Independiente del Valle',0,2);
INSERT INTO JOGO VALUES(117,'Group Matchday 1','7/04/2022','Tolima','Atlético Mineiro',0,2);
INSERT INTO JOGO VALUES(118,'Group Matchday 1','7/04/2022','Alianza Lima','River Plate',0,1);
INSERT INTO JOGO VALUES(119,'Group Matchday 1','7/04/2022','Talleres de Cordoba','Universidad Católica',1,0);
INSERT INTO JOGO VALUES(120,'Group Matchday 1','6/04/2022','Caracas','Atlético PR',0,0);
INSERT INTO JOGO VALUES(121,'Group Matchday 1','6/04/2022','Always Ready','Corinthians',2,0);
INSERT INTO JOGO VALUES(122,'Group Matchday 1','6/04/2022','Deportivo Cali','Boca Juniors',2,0);
INSERT INTO JOGO VALUES(123,'Group Matchday 1','6/04/2022','Colón Santa Fe','Peñarol',2,1);
INSERT INTO JOGO VALUES(124,'Group Matchday 1','6/04/2022','Olimpia','Cerro Porteño',0,0);
INSERT INTO JOGO VALUES(125,'Group Matchday 1','6/04/2022','Sporting Cristal','Flamengo',0,2);
INSERT INTO JOGO VALUES(126,'Qualifying Match','18/03/2022','The Strongest','Universidad Católica del Ecuador',2,1);
INSERT INTO JOGO VALUES(127,'Qualifying Match','17/03/2022','Olimpia','Fluminense',2,0);
INSERT INTO JOGO VALUES(128,'Qualifying Match','16/03/2022','Estudiantes','Everton',1,0);
INSERT INTO JOGO VALUES(129,'Qualifying Match','16/03/2022','Barcelona SC','América Mineiro',0,0);
INSERT INTO JOGO VALUES(130,'Qualifying Match','11/03/2022','Universidad Católica del Ecuador','The Strongest',0,0);
INSERT INTO JOGO VALUES(131,'Qualifying Match','10/03/2022','Fluminense','Olimpia',3,1);
INSERT INTO JOGO VALUES(132,'Qualifying Match','9/03/2022','Everton','Estudiantes',0,1);
INSERT INTO JOGO VALUES(133,'Qualifying Match','9/03/2022','América Mineiro','Barcelona SC',0,0);
INSERT INTO GOLO VALUES(1,45,'Flamengo','Gabriel Barbosa',1);
INSERT INTO GOLO VALUES(2,21,'Vélez Sarsfield','Lucas Pratto',2);
INSERT INTO GOLO VALUES(3,42,'Flamengo','Pedro',2);
INSERT INTO GOLO VALUES(4,68,'Flamengo','Marinho',2);
INSERT INTO GOLO VALUES(5,3,'Palmeiras','Gustavo Scarpa',3);
INSERT INTO GOLO VALUES(6,55,'Palmeiras','Gustavo Portillo',3);
INSERT INTO GOLO VALUES(7,64,'Atlético PR','Pablo',3);
INSERT INTO GOLO VALUES(8,85,'Atlético PR','David Terans',3);
INSERT INTO GOLO VALUES(9,32,'Flamengo','Pedro',4);
INSERT INTO GOLO VALUES(10,45,'Flamengo','Éverton Ribeiro',4);
INSERT INTO GOLO VALUES(11,61,'Flamengo','Pedro',4);
INSERT INTO GOLO VALUES(12,83,'Flamengo','Pedro',4);
INSERT INTO GOLO VALUES(13,23,'Atlético PR','Alex Santana',5);
INSERT INTO GOLO VALUES(14,90,'Atlético PR','Vitor Roque',6);
INSERT INTO GOLO VALUES(15,79,'Vélez Sarsfield','Julián Fernández',8);
INSERT INTO GOLO VALUES(16,52,'Flamengo','Pedro',9);
INSERT INTO GOLO VALUES(17,5,'Vélez Sarsfield','Lucas Janson',11);
INSERT INTO GOLO VALUES(18,73,'Vélez Sarsfield','Lucas Janson',11);
INSERT INTO GOLO VALUES(19,81,'Talleres de Cordoba','Michael Santos',11);
INSERT INTO GOLO VALUES(20,87,'Talleres de Cordoba','Rodrigo Garro',11);
INSERT INTO GOLO VALUES(21,90,'Vélez Sarsfield','Julián Fernández',11);
INSERT INTO GOLO VALUES(22,45,'Atlético Mineiro','Hulk',12);
INSERT INTO GOLO VALUES(23,47,'Atlético Mineiro','Murilo Cerqueira',12);
INSERT INTO GOLO VALUES(24,59,'Palmeiras','Murilo Cerqueira',12);
INSERT INTO GOLO VALUES(25,90,'Palmeiras','Danilo',12);
INSERT INTO GOLO VALUES(26,37,'Flamengo','Giorgian de Arrascaeta',13);
INSERT INTO GOLO VALUES(27,51,'Flamengo','Gabriel Barbosa',13);
INSERT INTO GOLO VALUES(28,9,'Estudiantes','Manuel Castro',14);
INSERT INTO GOLO VALUES(29,47,'Estudiantes','Manuel Castro',14);
INSERT INTO GOLO VALUES(30,57,'Estudiantes','Franco Zapiola',14);
INSERT INTO GOLO VALUES(31,47,'Talleres de Cordoba','Federico Girotti',16);
INSERT INTO GOLO VALUES(32,90,'Talleres de Cordoba','Angelo Martino',16);
INSERT INTO GOLO VALUES(33,5,'Flamengo','Pedro',17);
INSERT INTO GOLO VALUES(34,20,'Flamengo','Julián Quiñones',17);
INSERT INTO GOLO VALUES(35,47,'Flamengo','Pedro',17);
INSERT INTO GOLO VALUES(36,56,'Flamengo','Gabriel Barbosa',17);
INSERT INTO GOLO VALUES(37,63,'Tolima','Julián Quiñones',17);
INSERT INTO GOLO VALUES(38,67,'Flamengo','Pedro',17);
INSERT INTO GOLO VALUES(39,73,'Flamengo','Matheus França',17);
INSERT INTO GOLO VALUES(40,79,'Flamengo','Pedro',17);
INSERT INTO GOLO VALUES(41,37,'Cerro Porteño','Braian Samudio',18);
INSERT INTO GOLO VALUES(42,73,'Palmeiras','Rony',18);
INSERT INTO GOLO VALUES(43,75,'Palmeiras','Bren Lopes',18);
INSERT INTO GOLO VALUES(44,78,'Palmeiras','Gustavo Gómez',18);
INSERT INTO GOLO VALUES(45,83,'Palmeiras','Rony',18);
INSERT INTO GOLO VALUES(46,79,'Atlético Mineiro','Hulk',20);
INSERT INTO GOLO VALUES(47,45,'Libertad','Roque Cantero',21);
INSERT INTO GOLO VALUES(48,90,'Atlético PR','Rômulo Cardoso',21);
INSERT INTO GOLO VALUES(49,55,'Fortaleza','Silvio Romero',22);
INSERT INTO GOLO VALUES(50,63,'Estudiantes','Leandro Díaz',22);
INSERT INTO GOLO VALUES(51,15,'Vélez Sarsfield','Lucas Janson',23);
INSERT INTO GOLO VALUES(52,61,'Colón Santa Fe','Ramón Ábila',24);
INSERT INTO GOLO VALUES(53,87,'Talleres de Cordoba','Alan Franco',24);
INSERT INTO GOLO VALUES(54,60,'Palmeiras','Rony',25);
INSERT INTO GOLO VALUES(55,69,'Palmeiras','Rony',25);
INSERT INTO GOLO VALUES(56,87,'Palmeiras','Murilo Cerqueira',25);
INSERT INTO GOLO VALUES(57,17,'Flamengo','Andreas Pereira',26);
INSERT INTO GOLO VALUES(58,16,'Atlético Mineiro','Ademir',28);
INSERT INTO GOLO VALUES(59,58,'Emelec','Sebestián Rodríguez',28);
INSERT INTO GOLO VALUES(60,6,'Atlético PR','Vitor Roque',29);
INSERT INTO GOLO VALUES(61,20,'Libertad','Héctor Villalba',29);
INSERT INTO GOLO VALUES(62,32,'Atlético PR','Nicolás Hernández',29);
INSERT INTO EVENTO VALUES(1,'Substituição',20,1);
INSERT INTO EVENTO VALUES(2,'Cartão',28,1);
INSERT INTO EVENTO VALUES(3,'Cartão',43,1);
INSERT INTO EVENTO VALUES(4,'Cartão',43,1);
INSERT INTO EVENTO VALUES(5,'Substituição',46,1);
INSERT INTO EVENTO VALUES(6,'Substituição',57,1);
INSERT INTO EVENTO VALUES(7,'Substituição',57,1);
INSERT INTO EVENTO VALUES(8,'Substituição',65,1);
INSERT INTO EVENTO VALUES(9,'Cartão',68,1);
INSERT INTO EVENTO VALUES(10,'Substituição',71,1);
INSERT INTO EVENTO VALUES(11,'Cartão',73,1);
INSERT INTO EVENTO VALUES(12,'Cartão',75,1);
INSERT INTO EVENTO VALUES(13,'Substituição',75,1);
INSERT INTO EVENTO VALUES(14,'Substituição',84,1);
INSERT INTO EVENTO VALUES(15,'Substituição',84,1);
INSERT INTO EVENTO VALUES(16,'Cartão',51,2);
INSERT INTO EVENTO VALUES(17,'Cartão',58,2);
INSERT INTO EVENTO VALUES(18,'Substituição',59,2);
INSERT INTO EVENTO VALUES(19,'Substituição',60,2);
INSERT INTO EVENTO VALUES(20,'Substituição',60,2);
INSERT INTO EVENTO VALUES(21,'Cartão',62,2);
INSERT INTO EVENTO VALUES(22,'Substituição',63,2);
INSERT INTO EVENTO VALUES(23,'Substituição',63,2);
INSERT INTO EVENTO VALUES(24,'Substituição',63,2);
INSERT INTO EVENTO VALUES(25,'Substituição',70,2);
INSERT INTO EVENTO VALUES(26,'Substituição',84,2);
INSERT INTO EVENTO VALUES(27,'Substituição',84,2);
INSERT INTO EVENTO VALUES(28,'Substituição',84,2);
INSERT INTO EVENTO VALUES(29,'Cartão',90,2);
INSERT INTO EVENTO VALUES(30,'Cartão',90,2);
INSERT INTO EVENTO VALUES(31,'Cartão',27,3);
INSERT INTO EVENTO VALUES(32,'Cartão',40,3);
INSERT INTO EVENTO VALUES(33,'Cartão',42,3);
INSERT INTO EVENTO VALUES(34,'Cartão',45,3);
INSERT INTO EVENTO VALUES(35,'Substituição',46,3);
INSERT INTO EVENTO VALUES(36,'Substituição',46,3);
INSERT INTO EVENTO VALUES(37,'Substituição',46,3);
INSERT INTO EVENTO VALUES(38,'Substituição',46,3);
INSERT INTO EVENTO VALUES(39,'Substituição',63,3);
INSERT INTO EVENTO VALUES(40,'Cartão',67,3);
INSERT INTO EVENTO VALUES(41,'Substituição',79,3);
INSERT INTO EVENTO VALUES(42,'Substituição',79,3);
INSERT INTO EVENTO VALUES(43,'Cartão',81,3);
INSERT INTO EVENTO VALUES(44,'Substituição',87,3);
INSERT INTO EVENTO VALUES(45,'Substituição',87,3);
INSERT INTO EVENTO VALUES(46,'Substituição',90,3);
INSERT INTO EVENTO VALUES(47,'Cartão',90,3);
INSERT INTO EVENTO VALUES(48,'Cartão',34,4);
INSERT INTO EVENTO VALUES(49,'Cartão',54,4);
INSERT INTO EVENTO VALUES(50,'Substituição',65,4);
INSERT INTO EVENTO VALUES(51,'Substituição',65,4);
INSERT INTO EVENTO VALUES(52,'Cartão',67,4);
INSERT INTO EVENTO VALUES(53,'Cartão',68,4);
INSERT INTO EVENTO VALUES(54,'Substituição',71,4);
INSERT INTO EVENTO VALUES(55,'Cartão',74,4);
INSERT INTO EVENTO VALUES(56,'Substituição',75,4);
INSERT INTO EVENTO VALUES(57,'Substituição',79,4);
INSERT INTO EVENTO VALUES(58,'Cartão',84,4);
INSERT INTO EVENTO VALUES(59,'Substituição',85,4);
INSERT INTO EVENTO VALUES(60,'Substituição',85,4);
INSERT INTO EVENTO VALUES(61,'Substituição',85,4);
INSERT INTO EVENTO VALUES(62,'Cartão',90,4);
INSERT INTO EVENTO VALUES(63,'Cartão',90,4);
INSERT INTO EVENTO VALUES(64,'Substituição',52,5);
INSERT INTO EVENTO VALUES(65,'Cartão',58,5);
INSERT INTO EVENTO VALUES(66,'Cartão',58,5);
INSERT INTO EVENTO VALUES(67,'Substituição',64,5);
INSERT INTO EVENTO VALUES(68,'Cartão',70,5);
INSERT INTO EVENTO VALUES(69,'Substituição',84,5);
INSERT INTO EVENTO VALUES(70,'Substituição',84,5);
INSERT INTO EVENTO VALUES(71,'Substituição',84,5);
INSERT INTO EVENTO VALUES(72,'Substituição',85,5);
INSERT INTO EVENTO VALUES(73,'Substituição',85,5);
INSERT INTO EVENTO VALUES(74,'Substituição',86,5);
INSERT INTO EVENTO VALUES(75,'Substituição',90,5);
INSERT INTO EVENTO VALUES(76,'Substituição',90,5);
INSERT INTO CARTAO VALUES(1,'Amarelo','Atlético PR','Pedro Henrique',2);
INSERT INTO CARTAO VALUES(2,'Amarelo','Atlético PR','Alex Santana',3);
INSERT INTO CARTAO VALUES(3,'Vermelho','Atlético PR','Pedro Henrique',4);
INSERT INTO CARTAO VALUES(4,'Amarelo','Flamengo','Giorgian de Arrascaeta',9);
INSERT INTO CARTAO VALUES(5,'Amarelo','Atlético PR','Rômulo Cardoso',11);
INSERT INTO CARTAO VALUES(6,'Amarelo','Flamengo','Arturo Vidal',12);
INSERT INTO CARTAO VALUES(7,'Amarelo','Flamengo','Filipe Luís',16);
INSERT INTO CARTAO VALUES(8,'Amarelo','Flamengo','Arturo Vidal',17);
INSERT INTO CARTAO VALUES(9,'Amarelo','Vélez Sarsfield','Nicolás Garayalde',21);
INSERT INTO CARTAO VALUES(10,'Amarelo','Vélez Sarsfield','Mateo Seoane',29);
INSERT INTO CARTAO VALUES(11,'Amarelo','Vélez Sarsfield','Miguel Brizuela',30);
INSERT INTO CARTAO VALUES(12,'Amarelo','Atlético PR','Alex Santana',31);
INSERT INTO CARTAO VALUES(13,'Amarelo','Palmeiras','Gabriel Menino',32);
INSERT INTO CARTAO VALUES(14,'Amarelo','Atlético PR','Agustín Canobbio',33);
INSERT INTO CARTAO VALUES(15,'Vermelho','Palmeiras','Murilo Cerqueira',34);
INSERT INTO CARTAO VALUES(16,'Amarelo','Atlético PR','Pedrinho',40);
INSERT INTO CARTAO VALUES(17,'Amarelo','Atlético PR','Thiago Heleno',43);
INSERT INTO CARTAO VALUES(18,'Amarelo','Palmeiras','Weverton',47);
INSERT INTO CARTAO VALUES(19,'Amarelo','Flamengo','Gabriel Barbosa',48);
INSERT INTO CARTAO VALUES(20,'Amarelo','Vélez Sarsfield','Valentín Gómez',49);
INSERT INTO CARTAO VALUES(21,'Amarelo','Flamengo','Thiago Maia',52);
INSERT INTO CARTAO VALUES(22,'Amarelo','Vélez Sarsfield','Matías De los Santos',53);
INSERT INTO CARTAO VALUES(23,'Amarelo','Flamengo','David Luiz',55);
INSERT INTO CARTAO VALUES(24,'Amarelo','Flamengo','Léo Pereira',58);
INSERT INTO CARTAO VALUES(25,'Amarelo','Flamengo','Erick Pulgar',62);
INSERT INTO CARTAO VALUES(26,'Amarelo','Vélez Sarsfield','Mateo Seoane',63);
INSERT INTO CARTAO VALUES(27,'Amarelo','Palmeiras','Zé Rafael',65);
INSERT INTO CARTAO VALUES(28,'Amarelo','Atlético PR','Hugo Moura',66);
INSERT INTO CARTAO VALUES(29,'Vermelho','Atlético PR','Hugo Moura',68);
INSERT INTO SUBSTITUICAO VALUES(1,'Flamengo','Ayrton Lucas','Filipe Luís',1);
INSERT INTO SUBSTITUICAO VALUES(2,'Atlético PR','Matheus Nascimento','Alex Santana',5);
INSERT INTO SUBSTITUICAO VALUES(3,'Atlético PR','Agustín Canobbio','Vítor Bueno',6);
INSERT INTO SUBSTITUICAO VALUES(4,'Atlético PR','Rômulo Cardoso','Vitinho',7);
INSERT INTO SUBSTITUICAO VALUES(5,'Atlético PR','Pablo','Vitor Roque',8);
INSERT INTO SUBSTITUICAO VALUES(6,'Flamengo','Arturo Vidal','Thiago Maia',10);
INSERT INTO SUBSTITUICAO VALUES(7,'Atlético PR','David Terans','Hugo Moura',13);
INSERT INTO SUBSTITUICAO VALUES(8,'Flamengo','Everton Soares','Gabriel Barbosa',14);
INSERT INTO SUBSTITUICAO VALUES(9,'Flamengo','Victor Hugo','Giorgian de Arrascaeta',15);
INSERT INTO SUBSTITUICAO VALUES(10,'Vélez Sarsfield','Julián Fernández','Luca Orellano',18);
INSERT INTO SUBSTITUICAO VALUES(11,'Vélez Sarsfield','Walter Bou','Lucas Pratto',19);
INSERT INTO SUBSTITUICAO VALUES(12,'Vélez Sarsfield','Abiel Osorio','José Florentín',20);
INSERT INTO SUBSTITUICAO VALUES(13,'Flamengo','Ayrton Lucas','Filipe Luís',22);
INSERT INTO SUBSTITUICAO VALUES(14,'Flamengo','Marinho','Everton Soares',23);
INSERT INTO SUBSTITUICAO VALUES(15,'Flamengo','Erick Pulgar','Arturo Vidal',24);
INSERT INTO SUBSTITUICAO VALUES(16,'Vélez Sarsfield','Mateo Seoane','Santiago Cáseres',25);
INSERT INTO SUBSTITUICAO VALUES(17,'Flamengo','Guillermo Varela','Éverton Ribeiro',26);
INSERT INTO SUBSTITUICAO VALUES(18,'Flamengo','Diego','Giorgian de Arrascaeta',27);
INSERT INTO SUBSTITUICAO VALUES(19,'Vélez Sarsfield','Santiago Castro','Lucas Janson',28);
INSERT INTO SUBSTITUICAO VALUES(20,'Atlético PR','David Terans','Alex Santana',35);
INSERT INTO SUBSTITUICAO VALUES(21,'Atlético PR','Pedrinho','Abner Vinícius',36);
INSERT INTO SUBSTITUICAO VALUES(22,'Atlético PR','Rômulo Cardoso','Agustín Canobbio',37);
INSERT INTO SUBSTITUICAO VALUES(23,'Palmeiras','Luan Garcia','Bruno Tabata',38);
INSERT INTO SUBSTITUICAO VALUES(24,'Atlético PR','Pablo','Erick',39);
INSERT INTO SUBSTITUICAO VALUES(25,'Palmeiras','Mayke','Marcos Rocha',41);
INSERT INTO SUBSTITUICAO VALUES(26,'Palmeiras','Wesley','Rony',42);
INSERT INTO SUBSTITUICAO VALUES(27,'Palmeiras','Miguel Merentiel','Joaquín Piquerez',44);
INSERT INTO SUBSTITUICAO VALUES(28,'Palmeiras','Eduard Atuesta','Gabriel Menino',45);
INSERT INTO SUBSTITUICAO VALUES(29,'Atlético PR','Matheus Fernandes','Vitor Roque',46);
INSERT INTO SUBSTITUICAO VALUES(30,'Vélez Sarsfield','Mateo Seoane','Santiago Cáseres',50);
INSERT INTO SUBSTITUICAO VALUES(31,'Vélez Sarsfield','Abiel Osorio','Walter Bou',51);
INSERT INTO SUBSTITUICAO VALUES(32,'Flamengo','Arturo Vidal','Thiago Maia',54);
INSERT INTO SUBSTITUICAO VALUES(33,'Vélez Sarsfield','Julián Fernández','Luca Orellano',56);
INSERT INTO SUBSTITUICAO VALUES(34,'Flamengo','Erick Pulgar','Giorgian de Arrascaeta',57);
INSERT INTO SUBSTITUICAO VALUES(35,'Flamengo','Everton Soares','Gabriel Barbosa',59);
INSERT INTO SUBSTITUICAO VALUES(36,'Flamengo','Diego','Éverton Ribeiro',60);
INSERT INTO SUBSTITUICAO VALUES(37,'Flamengo','Victor Hugo','João Gomes',61);
INSERT INTO SUBSTITUICAO VALUES(38,'Palmeiras','Bruno Tabata','Raphael Veiga',64);
INSERT INTO SUBSTITUICAO VALUES(39,'Palmeiras','Wesley','José Lopéz',67);
INSERT INTO SUBSTITUICAO VALUES(40,'Palmeiras','Raphael Navarro','Rony',69);
INSERT INTO SUBSTITUICAO VALUES(41,'Palmeiras','Mayke','Marcos Rocha',70);
INSERT INTO SUBSTITUICAO VALUES(42,'Palmeiras','Eduard Atuesta','Zé Rafael',71);
INSERT INTO SUBSTITUICAO VALUES(43,'Atlético PR','Pablo','Vitor Roque',72);
INSERT INTO SUBSTITUICAO VALUES(44,'Atlético PR','Rômulo Cardoso','Agustín Canobbio',73);
INSERT INTO SUBSTITUICAO VALUES(45,'Atlético PR','Tomás Cuello','Vitinho',74);
INSERT INTO SUBSTITUICAO VALUES(46,'Atlético PR','Erick','Alex Santana',75);
INSERT INTO SUBSTITUICAO VALUES(47,'Atlético PR','Léo Cittadini','Fernandinho',76);
INSERT INTO ESTADIO VALUES(1,'Estadio Monumental','Equador',1);
INSERT INTO ESTADIO VALUES(2,'Maracanã','Brasil',2);
INSERT INTO ESTADIO VALUES(3,'Allianz Parque','Brasil',3);
INSERT INTO ESTADIO VALUES(4,'Estádio José Amalfitani','Argentina',4);
INSERT INTO ESTADIO VALUES(5,'Arena da Baixada','Brasil',5);